classification:
  labels_path: 'labels.txt'
  label_names_path: 'label_names.txt'
  shape: 100
  model_path: 'data/classification/models/model'
  save_trained_model: true
  save_trained_model_path: 'data/classification/models/new_model'
  test_data_path: 'data/classification/test'
  train_data_path: 'data/classification/train'
  datasets_augmentation:
    augment_train_dataset: true
    augment_type: 0

detection:
  batch_size: 4
  shape: 512
  epochs: 10
  first_object_class_id: 1
  data_path: 'data/detection/'
  labels_path: 'labels.txt'
  train_data_annotations_path: 'data/detection/train.csv'
  validation_data_annotations_path: 'data/detection/test.csv'
  model_path: 'data/detection/models/fasterrcnn/model15.pth'
  model_dir_path: 'data/detection/models/fasterrcnn'
  save_plot_after_x_epochs: 1
  save_model_after_x_epochs: 1
  detection_threshold: 0.6
  datasets_augmentation:
    augment_datasets: true
    augment_type: 0
    combine_randomly: false

segmentation:
  labels_to_detect:
    - 'TrafficLight'
  load_model_path: 'data/detection/enet/model.net'
  labels_path: 'data/detection/enet/classes.txt'
  colors_path: 'data/detection/enet/colors.txt'
  detection_min_object_area: 1000
  masked_image_opacity: 0.3

startup:
  seed: 1
  mode_selected_option: null
  function_selected_option: null
  detection_and_classification_optional_semantic_segmentation: null
  detection_and_classification_path: 'data/test/images'
  detection_and_classification_videos_path: 'data/test/videos'
  classification_path: 'data/test/signs'
  semantic_segmentation_path: 'data/test/images'